---
title: "DSC520 Week10 Exercise 10.2"
author: "Anjani Bonda"
date: February 19th 2022
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project: Fit a Logistic Regression model to Thoraric Surgery Binary Dataset

```{r}
library(foreign)
library(caTools)

setwd("/Users/anjanibonda/DSC520/dsc520")
# Load Thoraric Surgery Dataset 
thoraric_surgery_df <- read.arff("data/ThoraricSurgery.arff")
# Check structure of thoraric_surgery_df
str(thoraric_surgery_df)
# Check sample rows of thoraric_surgery_df
head(thoraric_surgery_df)
# Fit the LR model to the Thoraric Surgery Dataset
lrmodel <- glm(Risk1Yr ~ .,data = thoraric_surgery_df, family = 'binomial')
# Check the summary of the model
summary(lrmodel)

## As All of the below variables have lower p-value, below might be the good indicators whether a patient
## survives for 1 yr (the variable - Risk1Yr) post the surgery.
# PRE5
# PRE9T
# PRE140C13
# PRE140C14
# PRE17T
# PRE30T

# Split the data into 2 datasets - test and train
split <- sample.split(thoraric_surgery_df, SplitRatio = 0.8)
split

train <- subset(thoraric_surgery_df, split=="TRUE")
test <- subset(thoraric_surgery_df, split=="FALSE")
# Fit the model to the test dataset
res <- predict(lrmodel, test, type="response")
res
# Fit the model to the train dataset
res <- predict(lrmodel, train, type="response")
res
# Validate the model using confusion matrix
conf_matrix <- table(Actual_Value=train$Risk1Yr, Predicted_Value= res>0.5)
conf_matrix
# Check Accuracy of the model
(conf_matrix[[1,1]] + conf_matrix[[2,2]]) / sum(conf_matrix)
## Conclusion: The Accuracy of the model is ~84%
```