---
title: "DSC520 Week10 Exercise 10.3"
author: "Anjani Bonda"
date: February 19th 2022
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project: Impact of AirBnB on rental home prices in Columbus, OH

```{r}
library(readxl)
library(dplyr)
library(plyr)
library(tidyverse)
library(ggplot2)

setwd("/Users/anjanibonda/DSC520/dsc520")

# Above data set contains information across US cities
# Filtering the data based on Columbus city
library(readr)
airbnb_columbus_df <- readr::read_csv('data/airbnb-listings.csv')
str(airbnb_columbus_df)
summary(airbnb_columbus_df)

## Load the Affordable rental housing dataset
# housing_df=read.csv("Affordable_Rental_Housing_Developments.csv")
# glimpse(housing_df)

## Load the Average rent Columbus neighborhood dataset 
avg_rent_df <- read_excel("data/Avg_rent_columbus_neighbourhood.xlsx")
glimpse(avg_rent_df)

#Merge the airbnb df with rental housing df based on neighbourhood
#merged_df <- left_join(airbnb_columbus_df,avg_rent_df,by="neighbourhood_cleansed" )
#glimpse(merged_df)
#head(merged_df)

#Merge the above df with Average rent df based on neighbourhood
merged_df <- inner_join(x=airbnb_columbus_df,y=avg_rent_df,by=c("neighbourhood_cleansed") )
glimpse(merged_df)

# By looking at the data we can conclude that:
# Variable id is just an identifier which can be ignored.
# We can factor the field room.type - Private room,Entire home/apt,Hotel room, Shared room
# We can drop the host.id and host.name,neighbourhood.group,name fields from the dataset
# We can drop fields like last.review,number.of.reviews, reviews.per.month,calculated.host.listings.count

#Average rent Columbus neighborhood data
# Rename the Average Rent to Average_Rent

# Apply above transformation to the dataframe
final_df <- subset(merged_df, select = c("neighbourhood_cleansed",
                                         "latitude",
                                         "longitude",
                                         "room_type",
                                         "price","minimum_nights",
                                         "availability_365",
                                         "property_type",
                                         "Average Rent") )
glimpse(final_df)

#Rename Average Rent to Average_Rent
colnames(final_df)[9] <- "Average_Rent"

# Checking the summary of data set to gauge the value range of each numerical variable
summary(final_df)

# Range of values prices are varies from 0 to 10000. 
# It looks like there are outliers in the field.
# Range of values minimum_nights varies from 1 to 365. 
# It looks like there are outliers in the field.
# Range of values for availability_365 varies from 0 to 365. 


#Calculate the 30 days price for airbnb property.
final_df$airbnb_30_days_price=as.numeric(final_df$price) * 30
summary(final_df)

#Check missing values
apply(final_df, 2, function(x) any(is.na(x)))


## 2.What does the final data set look like?
glimpse(final_df)

## 3. Questions for future steps.
# a) Need to learn how to visualize more than two variables. 
# b) Need to learn application of variable scaling and techniques. 
# c) Need to learn how lm() function takes care of variable scaling.
# d) Need to learn correlation between different variables.

## 4.What information is not self-evident?
# To uncover new information in the data that is not self-evident -
# 1. visualize data to uncover patterns and trends
# 2. correlation among variables
# 3. Check data distribution of variables
# 4. detect outliers and influencial cases
# 5.What are different ways you could look at this data?

# Checking relation between airbnb_30_days_price and Average_Rent using 
ggplot()
library(ggplot2)
ggplot(data = final_df, aes(x = airbnb_30_days_price, y = Average_Rent)) +
  geom_point() + geom_smooth(fill=NA)

# Checking relation between neighbourhood_cleansed and Average_Rent using 
ggplot()
library(ggplot2)
ggplot(data = final_df, aes(y = neighbourhood_cleansed, x = Average_Rent)) +
  geom_point() + geom_smooth(fill=NA)

# Checking relation between neighbourhood_cleansed and airbnb_30_days_price using 
ggplot()
library(ggplot2)
ggplot(data = final_df, aes(y = neighbourhood_cleansed, x = airbnb_30_days_price)) +
  geom_point() + geom_smooth(fill=NA)

# Identify the relationship between neighbourhood and prices here.
# Checking if data distribution of numeric variables is normal
# combining pipe operator between dplyr transformation and ggplot
final_df %>% select(airbnb_30_days_price, Average_Rent) %>%
  gather() %>%
  ggplot(., aes(sample = value)) +
  stat_qq() +
  facet_wrap(vars(key), scales ='free_y')

#None of the variables looks normally distributed
ggplot(data = final_df, aes(x = neighbourhood_cleansed , y = airbnb_30_days_price)) +
  geom_boxplot() + ylab("airbnb_30_days_price")

# We can see that there are so many outliers for many neighbourhoods
# thus data is not normally distributed
ggplot(data = final_df, aes(x = room_type , y = airbnb_30_days_price)) +
  geom_boxplot() + ylab("30 days price")

# We can see that there are so many outliers for room_type
# thus data is not normally distributed
ggplot(data = final_df, aes(x = property_type , y = Average_Rent)) +
  geom_boxplot() + ylab("Property Type")

# We can see that there are so many outliers for Property_Type
# thus data is not normally distributed

# 6.How do you plan to slice and dice the data?

unique(final_df[c("neighbourhood_cleansed")])

# I think need to slice the datasets by zip codes or neighbourhood to analyze 
# the data in more granular level

# How could you summarize your data to answer key questions?
library("ggpubr")

ggscatter(final_df, x = "airbnb_30_days_price", y = "Average_Rent", 
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Miles/(US) gallon", ylab = "Weight (1000 lbs)")

#a) What are the Airbnb rental prices for different areas in Chicago?
ggplot(data=final_df,aes(y=neighbourhood_cleansed)) + geom_histogram(stat = "count")

ggplot(aes(y=neighbourhood_cleansed,x=airbnb_30_days_price),data=final_df)+
  geom_point()

# b) What is the correlation between the Airbnb rental prices and Columbus 
# neighborhood rent prices?

cor(final_df$airbnb_30_days_price,final_df$Average_Rent)

# c)What are the average rent prices by the neighborhood?
ggplot(aes(y=neighbourhood_cleansed,x=mean(final_df$Average_Rent)),data=final_df)+
  geom_point()

#The average rent price is xxx per month
# d)What are the average rent prices for Airbnb by the neighborhood?

ggplot(aes(y=neighbourhood_cleansed,x=mean(airbnb_30_days_price)),data=final_df)+
  geom_point()

#The average airbnb price is xxxx per month

# e) What type of houses are most rented on Airbnb?
ggplot(data=final_df,aes(y=room_type)) + geom_histogram(stat ="count")

# f)What is the monthly rent from the Airbnb properties?
df1 <-final_df%>%select(neighbourhood_cleansed, airbnb_30_days_price, Average_Rent)
df1 %>% group_by(neighbourhood_cleansed) %>% summarize(mean_airbnb_30_days_price =
                                                         mean(airbnb_30_days_price))

#Airbnb monrthly average rent is xxxx
# Do you plan on incorporating any machine learning techniques to answer 
# your research questions? Explain.
# performing multiple linear regression
# splitting the data into training and test set
library(caTools)
#mymodel_1 <-lm(airbnb_30_days_price ~ neighbourhood_cleansed,data = final_df)
#summary(mymodel_1)

#mymodel_2 <-lm(airbnb_30_days_price ~ Zip.Code,data = final_df)
#summary(mymodel_2)

# Questions for future steps?
# # Iam still working on fixing my data for the datasets being used here. 
# Might need to few more variables especially zip codes which I am missing currently in my data.
# I would like to plot the airbnb properties on map
# I think I need to look for more data to determine the correlation and to 
# predict prices accurately
```