---
title: "Assignment 2.2"
author: "Anjani Bonda"
date: "01/06/2023"
output:
  pdf_document: default
---

```{r eval=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## These two weeks we are going to be focused on line charts and step charts using various tools to create these visualizations. You must consolidate all the charts into ONE document with each chart labeled with the type of chart and technology - for example: Python - Bar Chart.  
```{r eval=TRUE, echo=FALSE}
setwd("/Users/anjanibonda/Data-Science/DSC640/Week3_4_Visualization_Tools/")
# Import required packages
library('magrittr')

# Import data to be used for visualization
fileData = paste(getwd(), '/ex2-2/world-population.xlsm', sep = '')
population = xlsx::read.xlsx(fileData, sheetIndex = 1, stringsAsFactors = FALSE)

# Examine data
print(head(population))

```

### Line Graph

```{r eval=TRUE, echo=FALSE}
options(repr.plot.width = 4, repr.plot.height = 3)

ggplot2::ggplot(data=population, ggplot2::aes(x=Year, y=Population)) + 
  ggplot2::labs(title = "R - Line Graph") +
  ggplot2::geom_line(linetype='solid', color='blue', size=1.2)
```

### Step Graph

```{r eval=TRUE, echo=FALSE}
# We need to reshape the data to long format for this purpose
ggplot2::ggplot(data=population, ggplot2::aes(x=Year, y=Population)) +
  ggplot2::labs(title = "R- Step Graph") +
  ggplot2::geom_step(linetype='solid', color='blue', size=1.2)
```

